[[headers]]
  # Apply to all routes
  for = "/*"

  # Security Headers
  [headers.values]
  Content-Security-Policy = "default-src 'self'"
  Feature-Policy = "autoplay 'none'; camera 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none'; midi 'none'; payment 'none'; vr 'none'"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
